const recipes = [
  {
    name: "Saag Aloo",
    ingredients: [
      "chilli",
      "mango chutney",
      "potato",
      "spinach",
      "tomato paste",
      "solid creamed coconut",
      "peas",
      "ginger and garlic paste",
      "turmeric",
      "veg stock",
      "Pittas",
      "cumin seeds",
      "Curry powder",
    ],
  },
  {
    name: "Black bean & sweet potato tortilla pockets",
    ingredients: [
      "leaf salad",
      "red wine vinegar",
      "Sweet potato",
      "tomato paste",
      "black beans",
      "paprika-ground",
      "veg stock",
      "cumin-ground",
      "tortillas",
      "mayo",
    ],
  },
  {
    name: "Sticky onion burger",
    ingredients: [
      "onion",
      "tomato",
      "lettuce",
      "potato",
      "ketchup",
      "cheese slices",
      "burger patties",
      "relish",
      "onion marmalade",
      "Burger buns",
    ],
  },
  {
    name: "Chick'n Dopiaza",
    ingredients: [
      "onion",
      "onion",
      "tomato",
      "tomato paste",
      "crispy onions",
      "indian bread of choice",
      "Veg stock",
      "Cumin-ground",
      "chick'n",
      "cultured coconut",
      "corriander-ground",
      "curry powder",
    ],
  },
  {
    name: "Cauliflower korma",
    ingredients: [
      "onion",
      "cauliflower",
      "garlic",
      "flaked almonds",
      "solid creamed coconut",
      "ginger paste",
      "rice",
      "turmeric",
      "veg stock",
      "cumin-ground",
      "curry powder",
    ],
  },
  {
    name: "Roasted cauliflower curry bake",
    ingredients: [
      "onions",
      "cauliflower",
      "cashew nuts",
      "mango chutney",
      "spinach",
      "potato",
      "solid creamed coconut",
      "turmeric",
      "veg stock",
      "fenugreek-ground",
      "curry powder",
    ],
  },
  {
    name: "Cocunut curry dal",
    ingredients: [
      "onion",
      "pepper-red",
      "solid creamed coconut",
      "lentils",
      "ginger & garlic paste",
      "green beans",
      "veg stock",
      "rice",
      "finely chopped tomotoes",
      "curry powder",
    ],
  },
  {
    name: "Butternut & cashew saag",
    ingredients: [
      "onion",
      "sultanas",
      "garlic",
      "cashews",
      "corriander",
      "spinach",
      "tomato paste",
      "solid creamed coconut",
      "peas",
      "rice",
      "ginger-fresh",
      "butternut",
      "veg stock",
      "curry powder",
    ],
  },
  {
    name: "Black bean & Corn Tacos",
    ingredients: [
      "onion",
      "onion",
      "chilli",
      "tomato",
      "lime",
      "corriander",
      "tomato paste",
      "sweetcorn",
      "black beans",
      "chipotle paste",
      "veg stock",
      "tortillas",
      "Guac",
    ],
  },
  {
    name: "Oven baked coconut veg curry",
    ingredients: [
      "cherry tomatoes",
      "corriander",
      "sweet potato",
      "tomato paste",
      "peas",
      "ginger paste",
      "turmeric",
      "green beans",
      "veg stock",
      "pittas",
      "cultured coconut",
      "curry powder",
    ],
  },
  {
    name: "Sweet potato & chickpea stew",
    ingredients: [
      "onion",
      "sultans",
      "garlic",
      "sweet potato",
      "chickpeas",
      "couscous",
      "veg stock",
      "cumin-ground",
      "finely chopped tomotoes",
    ],
  },
  {
    name: "Tofu pakoras with fries",
    ingredients: [
      "mango chutney",
      "corriander",
      "tofu",
      "cider vinegar",
      "chilli",
      "potato",
      "ginger-fresh",
      "turmeric",
      "veg stock",
      "mayo",
      "coleslaw",
      "curry powder",
      "cornflour",
    ],
  },
  {
    name: "Sweet potato & cashew coconut curry",
    ingredients: [
      "onion",
      "garlic",
      "cashews",
      "green beans",
      "ginger paste",
      "veg stock",
      "thai curry paste",
      "rice",
      "cultured coconut",
      "sweet potato-diced",
    ],
  },
  {
    name: "spicy noodle soup with Korean-style tofu",
    ingredients: [
      "spring onion",
      "tofu",
      "tamari soy sauce",
      "rice vinegar",
      "toasted sesame seeds",
      "rice noodles",
      "veg stock",
      "gochujang paste",
      "coleslaw",
      "cornflour",
      "Pho broth paste",
      "garlic clove",
    ],
  },
  {
    name: "Hoisan noodle stir fry",
    ingredients: [
      "onion",
      "pepper-red",
      "broccoli",
      "garlic clove",
      "spring onion",
      "cashews",
      "hoisan sauce",
      "soy sauce",
      "chilli flakes",
      "ginger-fresh",
      "udon noodles",
      "toasted sesame oil",
      "cornflour",
    ],
  },
  {
    name: "Tofu with yellow thai curry",
    ingredients: [
      "courgette",
      "cherry tomotoes",
      "curry powder",
      "corriander",
      "tofu",
      "tamari soy sauce",
      "tomato paste",
      "solid creamed coconut",
      "turmeric",
      "veg stock",
      "red thai curry paste",
      "rice",
      "garam masala",
      "cornflour",
    ],
  },
  {
    name: "Thai style coconut udon noodles",
    ingredients: [
      "onion",
      "pepper-yellow",
      "lime",
      "garlic",
      "soy sauce",
      "roasted peanuts",
      "green beans",
      "rice wine",
      "chestnut mushrooms",
      "solid creamed coconut",
      "ginger-fresh",
      "udon noodles",
      "veg stock",
      "sriracha",
    ],
  },
  {
    name: "Korean mince bulgogi",
    ingredients: [
      "garlic clove",
      "spring onion",
      "soy sauce",
      "ginger-fresh",
      "green beans",
      "sesame oil",
      "rice",
      "mince",
    ],
  },
  {
    name: "Lime tofu with sticky ginger",
    ingredients: [
      "onion",
      "lime",
      "garlic clove",
      "spinach",
      "tofu",
      "agave",
      "soy sauce",
      "black sesame seeds",
      "rice",
      "ginger-fresh",
      "veg stock",
      "cornflour",
    ],
  },
  {
    name: "korean style bulgogi rice salad",
    ingredients: [
      "lettuce",
      "mangetout",
      "tofu",
      "tamari sauce",
      "sesame seeds",
      "ginger & garlic paste",
      "gochugang paste",
      "rice",
      "cornflour",
    ],
  },
  {
    name: "Smoky tofu & herby rice bowl",
    ingredients: [
      "cucumber",
      "rocket",
      "coriander",
      "carrot",
      "tofu",
      "tamari soy sauce",
      "cider vinegar",
      "harissa paste",
      "paprika-ground",
      "mayo",
      "rice",
      "cornflour",
    ],
  },
  {
    name: "Hoisin mince & mushroom bowl",
    ingredients: [
      "chilli",
      "lettuce",
      "hoisin sauce",
      "soy sauce",
      "chestnut mushrooms",
      "sesame seeds",
      "crispy onions",
      "ginger & garlic paste",
      "mince",
      "rice",
    ],
  },
  {
    name: "Sichuan-style spicy black bean tofu",
    ingredients: [
      "onion",
      "garlic clove",
      "soy sauce",
      "spring onion",
      "spinach",
      "tofu",
      "chestnut mushrooms",
      "chilli flakes",
      "ginger-fresh",
      "black bean paste",
      "toasted sesame oil",
      "rice",
      "cornflour",
      "sriracha",
    ],
  },
  {
    name: "sweet chilli tofu with veg rice",
    ingredients: [
      "garlic clove",
      "carrots",
      "tofu",
      "agave nector",
      "soy sauce",
      "sesame seeds",
      "toasted sesame seeds",
      "peas",
      "rice",
      "chilli relish",
      "cornflour",
    ],
  },
  {
    name: "Tofu burger & chips",
    ingredients: [
      "spring onion",
      "carrot",
      "spiced chutney",
      "tofu",
      "hoisin sauce",
      "soy sauce",
      "rice vinegar",
      "toasted sesame seeds",
      "potato",
      "cabbage-shredded-red",
      "cornflour",
      "brioche buns",
    ],
  },
  {
    name: "Chilli bean cheeseburger",
    ingredients: [
      "chilli",
      "lettuce",
      "red wine vineger",
      "tomato paste",
      "potato",
      "cheese slice",
      "burger patties",
      "black beans",
      "paprika-ground",
      "burger buns",
      "cumin-ground",
    ],
  },
  {
    name: "Paella with crispy tofu",
    ingredients: [
      "lemon",
      "onion",
      "pepper",
      "saffron",
      "garlic",
      "tofu",
      "soy sauce",
      "tomato paste",
      "peas",
      "paprika-ground",
      "veg stock",
      "cumin",
      "paella rice",
    ],
  },
  {
    name: "Lentil enchiladas with cashew crema",
    ingredients: [
      "onion",
      "pepper-green",
      "lime",
      "garlic",
      "corriander",
      "cherry tomatoes",
      "cashews",
      "soy sauce",
      "tomato paste",
      "chilli flakes",
      "paprika-ground",
      "cumin",
      "tortillas",
      "lentils",
    ],
  },
  {
    name: "Marinara Tacos",
    ingredients: [
      "Onion",
      "garlic",
      "balsamic vinegar",
      "rocket",
      "tomato paste",
      "burger patties",
      "bread crumbs",
      "basil-dired",
      "tortillas",
    ],
  },
  {
    name: "Chilli con tofu and crispy tortillas",
    ingredients: [
      "soy sauce",
      "corriander",
      "red wine vinegar",
      "tofu",
      "avo",
      "black beans",
      "chipotle paste",
      "chilli flakes",
      "paprika-ground",
      "veg stock",
      "cumin-ground",
      "Nachos",
      "finely chopped tomatoes",
    ],
  },
  {
    name: "Oven baked chilli jacket potatoes",
    ingredients: [
      "garlic",
      "corriander",
      "vinegar",
      "chilli",
      "potato",
      "black beans",
      "butter beans",
      "chipotle paste",
      "paprika",
      "veg stock",
      "cumin seeds",
      "kidney beans",
      "finely chopped tomatoes",
    ],
  },
  {
    name: "Beany chilli salsa and rice",
    ingredients: [
      "onion",
      "pepper-red",
      "lime",
      "garlic clove",
      "corriander",
      "tomato paste",
      "chipotle paste",
      "paprika",
      "veg stock",
      "cumin-ground",
      "rice",
      "guac",
      "kidney beans",
    ],
  },
  {
    name: "Nachos",
    ingredients: [
      "tortillas chips",
      "salsa",
      "cheese",
      "guac",
      "soy mince",
      "onion",
      "cucumber",
      "tomato",
    ],
  },
  {
    name: "Lentil risotto",
    ingredients: [
      "onion",
      "pepper-red",
      "garlic",
      "rocket",
      "vinegar",
      "lentils",
      "oregano-dried",
      "veg stock",
      "creamy single oat",
      "finely chopped tomatoes",
    ],
  },
  {
    name: "Gnocchi",
    ingredients: [
      "onion",
      "gnocchi",
      "pepper",
      "spinach",
      "nooch",
      "soy chunks",
      "pesto",
    ],
  },
  {
    name: "Butternut grain bowl",
    ingredients: [
      "onion",
      "butternut",
      "pumpkin seeds",
      "tender stem broccoli",
      "kale",
      "agave",
      "vinegar",
      "tahini",
      "bulgar wheat",
      "chilli flakes",
      "oregano-dried",
      "white miso paste",
      "toasted sesame oil",
      "lentils",
    ],
  },
  {
    name: "chilli roasted squash",
    ingredients: [
      "onion",
      "lime",
      "basil",
      "roasted peanutes",
      "rocket",
      "corriander",
      "bulgar wheat",
      "soy sauce",
      "vinegar",
      "chickpeas",
      "chilli flakes",
      "ginger-fresh",
      "butternut",
      "toaste sesame oil",
    ],
  },
];

const aisles = {
  freshProduce: ["onion", "tomato", "spinach", "lime"],
  fridgeyStuff: ["tofu", "cheese"],
};

export { recipes, aisles };
